#pragma once

#define TENSIL_ARCHITECTURE_DATA_TYPE             TENSIL_DATA_TYPE_FP16BP8
#define TENSIL_ARCHITECTURE_ARRAY_SIZE            8
#define TENSIL_ARCHITECTURE_DRAM0_DEPTH           1048576
#define TENSIL_ARCHITECTURE_DRAM1_DEPTH           1048576
#define TENSIL_ARCHITECTURE_LOCAL_DEPTH           8192
#define TENSIL_ARCHITECTURE_ACCUMULATOR_DEPTH     2048
#define TENSIL_ARCHITECTURE_SIMD_REGISTERS_DEPTH  1
#define TENSIL_ARCHITECTURE_STRIDE0_DEPTH         8
#define TENSIL_ARCHITECTURE_STRIDE1_DEPTH         8
